In [2]:
import numpy as np
import pandas as pd 
import matplotlib as plt

In [3]:
movies = pd.read_csv("tmdb_5000_movies.csv")

In [4]:
credits = pd.read_csv("tmdb_5000_credits.csv")

In [5]:
movies.head(5)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [6]:
movies.describe()

,budget,id,popularity,revenue,runtime,vote_average,vote_count
count,4.803000e+03,4803.000000,4803.000000,4.803000e+03,4801.000000,4803.000000,4803.000000
mean,2.904504e+07,57165.484281,21.492301,8.226064e+07,106.875859,6.092172,690.217989
std,4.072239e+07,88694.614033,31.816650,1.628571e+08,22.611935,1.194612,1234.585891
min,0.000000e+00,5.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000
25%,7.900000e+05,9014.500000,4.668070,0.000000e+00,94.000000,5.600000,54.000000
50%,1.500000e+07,14629.000000,12.921594,1.917000e+07,103.000000,6.200000,235.000000
75%,4.000000e+07,58610.500000,28.313505,9.291719e+07,118.000000,6.800000,737.000000
max,3.800000e+08,459488.000000,875.581305,2.787965e+09,338.000000,10.000000,13752.000000

In [7]:
movies.info()

<class 'pandas.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   str
 2   homepage              1712 non-null   str
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   str
 5   original_language     4803 non-null   str
 6   original_title        4803 non-null   str
 7   overview              4800 non-null   str
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   str
 10  production_countries  4803 non-null   str
 11  release_date          4802 non-null   str
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   str
 15  status                4803 non-null   str
 16  tagline               3959 non-null   str
 17  title                 4803 non-null   str
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: float64(3), int64(4), str(13)
memory usage: 750.6 KB

In [8]:
movies.shape

(4803, 20)

In [9]:
movies = movies.merge(credits, on =  "title")

In [10]:
movies.shape

(4809, 23)

In [11]:
movies = movies[["movie_id","title","overview","genres","keywords","cast","crew"]]

In [12]:
movies.sample()

,movie_id,title,overview,genres,keywords,cast,crew
685,9955,Blades of Glory,When a much-publicized ice-skating scandal str...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 35, ""nam...","[{""id"": 271, ""name"": ""competition""}, {""id"": 20...","[{""cast_id"": 25, ""character"": ""Chazz Michael M...","[{""credit_id"": ""52fe4550c3a36847f80c7377"", ""de..."

In [13]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [14]:
movies = movies.dropna()

In [15]:
movies.isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [16]:
movies.shape

(4806, 7)

In [17]:
movies.duplicated().sum()

np.int64(0)

In [18]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [19]:
import ast
def convert(obj):
    lst=[]
    for i in ast.literal_eval(obj):
        lst.append(i["name"])
        
    return lst

In [20]:
movies.sample()

,movie_id,title,overview,genres,keywords,cast,crew
3691,68202,Without Men,The women of a remote Latin American town are ...,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...","[{""id"": 187056, ""name"": ""woman director""}]","[{""cast_id"": 4, ""character"": ""Rosalba"", ""credi...","[{""credit_id"": ""52fe4789c3a368484e0cc679"", ""de..."

In [21]:
movies["genres"] = movies["genres"].apply(convert)

In [22]:
movies.sample()

,movie_id,title,overview,genres,keywords,cast,crew
4580,308467,Roadside,"Dan Summers and his pregnant wife, Mindy, figh...","[Horror, Drama]",[],"[{""cast_id"": 1, ""character"": ""Dan Summers"", ""c...","[{""credit_id"": ""54850af6c3a3680b36001a86"", ""de..."

In [23]:
movies.isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [24]:
movies["keywords" ]= movies["keywords"].apply(convert)

In [25]:
import ast
def reduse(obj):
    lst=[]
    count= 0
    for i in ast.literal_eval(obj):
        if count != 3:
            lst.append(i["name"])
            count+=1
        else:
            break
        
    return lst

In [26]:
movies["cast"] = movies["cast"].apply(reduse)

In [27]:
movies.sample(5)

,movie_id,title,overview,genres,keywords,cast,crew
2959,1590,Copying Beethoven,A fictionalised exploration of Beethoven's lif...,[Drama],"[beethoven, woman director]","[Ed Harris, Diane Kruger, Matthew Goode]","[{""credit_id"": ""52fe4302c3a36847f80337af"", ""de..."
2793,59457,Womb,A woman's consuming love forces her to bear th...,"[Romance, Science Fiction]",[],"[Eva Green, Matt Smith, Lesley Manville]","[{""credit_id"": ""591009b8c3a36864d402c9c1"", ""de..."
3482,1443,The Virgin Suicides,A group of male friends become obsessed with f...,"[Drama, Romance]","[michigan, 1970s, youth, family, woman director]","[James Woods, Kathleen Turner, Kirsten Dunst]","[{""credit_id"": ""52fe42f8c3a36847f80308d5"", ""de..."
3349,57119,Jumping the Broom,Two very different families converge on Martha...,[Comedy],"[african american, wedding, class differences,...","[Paula Patton, Julie Bowen, Meagan Good]","[{""credit_id"": ""52fe4925c3a36847f818b353"", ""de..."
3444,21641,The Damned United,"Taking over Leeds United, Brian Clough's abras...",[Drama],"[england, leeds united, sport, brighton, socce...","[Michael Sheen, Timothy Spall, Colm Meaney]","[{""credit_id"": ""52fe4422c3a368484e0117e7"", ""de..."

In [28]:
l = ast.literal_eval(movies.iloc[0].crew)

In [29]:
list({cre["department"] for cre in l})

['Sound',
 'Crew',
 'Visual Effects',
 'Editing',
 'Production',
 'Art',
 'Costume & Make-Up',
 'Writing',
 'Lighting',
 'Directing',
 'Camera']

In [30]:
[cre for cre in l if cre["department"] == "Directing"]

[{'credit_id': '52fe48009251416c750ac9c3',
  'department': 'Directing',
  'gender': 2,
  'id': 2710,
  'job': 'Director',
  'name': 'James Cameron'}]

In [31]:
import ast
def directing(obj):
    lst=[]
    for i in ast.literal_eval(obj):
        if i["job"] == "Director":
            lst.append(i["name"])
            break
        
    return lst

In [32]:
movies["crew"]=movies["crew"].apply(directing)

In [33]:
movies.sample()

,movie_id,title,overview,genres,keywords,cast,crew
2370,522,Ed Wood,"The mostly true story of the legendary ""worst ...","[Comedy, Drama, History]","[individual, taxi, transsexuality, fortune tel...","[Johnny Depp, Martin Landau, Sarah Jessica Par...",[Tim Burton]

In [34]:
movies["overview"][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [35]:
movies["overview"]=movies["overview"].apply(lambda x:x.split())

In [36]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [37]:
movies["cast"]=movies["cast"].apply(lambda x:[i.replace(" ","") for i in x])
movies["crew"]=movies["crew"].apply(lambda x:[i.replace(" ","") for i in x])
movies["keywords"]=movies["keywords"].apply(lambda x:[i.replace(" ","") for i in x])
movies["genres"]=movies["genres"].apply(lambda x:[i.replace(" ","") for i in x])

In [38]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [39]:
movies["tags"] = movies["overview"]+movies["genres"]+movies["keywords"]+movies["cast"]+movies["crew"]

In [40]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [41]:
movies["tags"] = movies["tags"].apply(lambda x:" ".join(x))

In [42]:
movies["tags"] = movies["tags"].apply(lambda x:x.lower())

In [43]:
new_df = movies[["movie_id","title","tags"]]

In [44]:
new_df

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."
...,...,...,...
4804,9367,El Mariachi,el mariachi just wants to play his guitar and ...
4805,72766,Newlyweds,a newlywed couple's honeymoon is upended by th...
4806,231617,"Signed, Sealed, Delivered","""signed, sealed, delivered"" introduces a dedic..."
4807,126186,Shanghai Calling,when ambitious new york attorney sam is sent t...
4808,25975,My Date with Drew,ever since the second grade when he first saw ...

In [45]:
from sklearn.feature_extraction.text import CountVectorizer

In [46]:
cv = CountVectorizer(max_features=5000,stop_words="english")

In [47]:
vectors = cv.fit_transform(new_df["tags"]).toarray()

In [48]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], shape=(5000,))

In [49]:
import nltk
from nltk.stem.porter import PorterStemmer

ps = PorterStemmer()
print(ps.stem("playing"))

play

In [50]:
def stem(text):
    y  = []
    for i in text.split():
        y.append(ps.stem(i))
        
        return " ".join(y)

In [51]:
new_df["tags"] = new_df["tags"].apply(stem)

In [52]:
from sklearn.metrics.pairwise import cosine_similarity

In [53]:
similarity = cosine_similarity(vectors)

In [54]:
def recommend(movie):
    movie_index  = new_df[new_df["title"] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)),reverse=True , key = lambda x:x[1])[1:6]
    
    for i in movies_list:
        print(i[0])

In [55]:
def recommend(movie):
    movie = movie.strip()
    if movie not in new_df["title"].values:
        print(f"'{movie}' not found in the dataset.")
        return []

    movie_index = new_df[new_df["title"] == movie].index[0]
    distances = similarity[movie_index]
    similar_movies = sorted(
        list(enumerate(distances)),
        key=lambda x: x[1],
        reverse=True
    )[1:6]

    recommended = [new_df.iloc[idx]["title"] for idx, _ in similar_movies]
    print(recommended)
    return recommended

In [56]:
recommend("Aliens vs Predator: Requiem")

['Independence Daysaster', 'Slither', 'AVP: Alien vs. Predator', 'Predators', 'Edge of Tomorrow']

['Independence Daysaster',
 'Slither',
 'AVP: Alien vs. Predator',
 'Predators',
 'Edge of Tomorrow']

In [57]:
recommend("Avatar")

['Titan A.E.', 'Small Soldiers', 'Independence Day', "Ender's Game", 'Aliens vs Predator: Requiem']

['Titan A.E.',
 'Small Soldiers',
 'Independence Day',
 "Ender's Game",
 'Aliens vs Predator: Requiem']

In [58]:
recommend("Batman Begins")

['The Dark Knight', 'The Dark Knight Rises', 'Batman', 'Batman', 'Batman & Robin']

['The Dark Knight',
 'The Dark Knight Rises',
 'Batman',
 'Batman',
 'Batman & Robin']

In [59]:
import pickle


pickle.dump(new_df.to_dict(),open("movies_dict.pkl","wb"))

In [61]:
import pickle

with open("similarity.pkl", "wb") as file:
    pickle.dump(similarity, file)